config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :orders

  resources :order_items

  resources :customers

  resources :recipes

  resources :components

  resources :shipping_addresses

  resources :stock_types

  resources :stocks

  resources :suppliers

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :supplier
  belongs_to :stock_type
  has_and_belongs_to_many :components
end

app/models/stock_type.rb
class StockType < ActiveRecord::Base
  has_many :order_items
  has_many :stocks
  has_and_belongs_to_many :recipes
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:initial_quantity, :current_quantity, :unit, :purchase_date, :expiration_date, :purchase_price, :supplier, :batch_number, :supplier_id, :stock_type_id)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= simple_form_for(@stock) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :initial_quantity %>
    <%= f.input :current_quantity %>
    <%= f.input :unit %>
    <%= f.input :purchase_date %>
    <%= f.input :expiration_date %>
    <%= f.input :purchase_price %>
    <%= f.input :supplier %>
    <%= f.input :batch_number %>
    <%= f.association :supplier %>
    <%= f.association :stock_type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Listing stocks</h1>

<table>
  <thead>
    <tr>
      <th>Initial quantity</th>
      <th>Current quantity</th>
      <th>Unit</th>
      <th>Purchase date</th>
      <th>Expiration date</th>
      <th>Purchase price</th>
      <th>Supplier</th>
      <th>Batch number</th>
      <th>Supplier</th>
      <th>Stock type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.initial_quantity %></td>
        <td><%= stock.current_quantity %></td>
        <td><%= stock.unit %></td>
        <td><%= stock.purchase_date %></td>
        <td><%= stock.expiration_date %></td>
        <td><%= stock.purchase_price %></td>
        <td><%= stock.supplier %></td>
        <td><%= stock.batch_number %></td>
        <td><%= stock.supplier %></td>
        <td><%= stock.stock_type %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Initial quantity:</strong>
  <%= @stock.initial_quantity %>
</p>

<p>
  <strong>Current quantity:</strong>
  <%= @stock.current_quantity %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @stock.unit %>
</p>

<p>
  <strong>Purchase date:</strong>
  <%= @stock.purchase_date %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @stock.expiration_date %>
</p>

<p>
  <strong>Purchase price:</strong>
  <%= @stock.purchase_price %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @stock.supplier %>
</p>

<p>
  <strong>Batch number:</strong>
  <%= @stock.batch_number %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @stock.supplier %>
</p>

<p>
  <strong>Stock type:</strong>
  <%= @stock.stock_type %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>