config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :orders

  resources :order_items

  resources :customers

  resources :recipes

  resources :components

  resources :shipping_addresses

  resources :stock_types

  resources :stocks

  resources :suppliers

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/component.rb
class Component < ActiveRecord::Base
  has_and_belongs_to_many :stocks
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  has_many :shipping_addresses
  validates_formatting_of :email, using: :email
  validates_formatting_of :phone, using: :us_phone
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_one :shipping_address
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :stock_type
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_and_belongs_to_many :stock_types
end

app/models/shipping_address.rb
class ShippingAddress < ActiveRecord::Base
  belongs_to :customer
  belongs_to :order
  validates_formatting_of :zip, using: :us_zip
  validates_formatting_of :email, using: :email
  validates_formatting_of :phone, using: :us_phone
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :supplier
  belongs_to :stock_type
  has_and_belongs_to_many :components
end

app/models/stock_type.rb
class StockType < ActiveRecord::Base
  has_many :order_items
  has_many :stocks
  has_and_belongs_to_many :recipes
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_many :stocks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/shipping_addresses_controller.rb
class ShippingAddressesController < ApplicationController
  before_action :set_shipping_address, only: [:show, :edit, :update, :destroy]

  # GET /shipping_addresses
  # GET /shipping_addresses.json
  def index
    @shipping_addresses = ShippingAddress.all
  end

  # GET /shipping_addresses/1
  # GET /shipping_addresses/1.json
  def show
  end

  # GET /shipping_addresses/new
  def new
    @shipping_address = ShippingAddress.new
  end

  # GET /shipping_addresses/1/edit
  def edit
  end

  # POST /shipping_addresses
  # POST /shipping_addresses.json
  def create
    @shipping_address = ShippingAddress.new(shipping_address_params)

    respond_to do |format|
      if @shipping_address.save
        format.html { redirect_to @shipping_address, notice: 'Shipping address was successfully created.' }
        format.json { render :show, status: :created, location: @shipping_address }
      else
        format.html { render :new }
        format.json { render json: @shipping_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipping_addresses/1
  # PATCH/PUT /shipping_addresses/1.json
  def update
    respond_to do |format|
      if @shipping_address.update(shipping_address_params)
        format.html { redirect_to @shipping_address, notice: 'Shipping address was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipping_address }
      else
        format.html { render :edit }
        format.json { render json: @shipping_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipping_addresses/1
  # DELETE /shipping_addresses/1.json
  def destroy
    @shipping_address.destroy
    respond_to do |format|
      format.html { redirect_to shipping_addresses_url, notice: 'Shipping address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipping_address
      @shipping_address = ShippingAddress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipping_address_params
      params.require(:shipping_address).permit(:first_name, :last_name, :address_1, :address_2, :city, :state, :country, :zip, :email, :phone, :customer_id, :order_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/shipping_addresses/_form.html.erb
<%= simple_form_for(@shipping_address) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :address_1 %>
    <%= f.input :address_2 %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :country %>
    <%= f.input :zip %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.association :customer %>
    <%= f.association :order %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shipping_addresses/edit.html.erb
<h1>Editing shipping_address</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipping_address %> |
<%= link_to 'Back', shipping_addresses_path %>

app/views/shipping_addresses/index.html.erb
<h1>Listing shipping_addresses</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Zip</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Customer</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shipping_addresses.each do |shipping_address| %>
      <tr>
        <td><%= shipping_address.first_name %></td>
        <td><%= shipping_address.last_name %></td>
        <td><%= shipping_address.address_1 %></td>
        <td><%= shipping_address.address_2 %></td>
        <td><%= shipping_address.city %></td>
        <td><%= shipping_address.state %></td>
        <td><%= shipping_address.country %></td>
        <td><%= shipping_address.zip %></td>
        <td><%= shipping_address.email %></td>
        <td><%= shipping_address.phone %></td>
        <td><%= shipping_address.customer %></td>
        <td><%= shipping_address.order %></td>
        <td><%= link_to 'Show', shipping_address %></td>
        <td><%= link_to 'Edit', edit_shipping_address_path(shipping_address) %></td>
        <td><%= link_to 'Destroy', shipping_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipping address', new_shipping_address_path %>

app/views/shipping_addresses/new.html.erb
<h1>New shipping_address</h1>

<%= render 'form' %>

<%= link_to 'Back', shipping_addresses_path %>

app/views/shipping_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @shipping_address.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @shipping_address.last_name %>
</p>

<p>
  <strong>Address 1:</strong>
  <%= @shipping_address.address_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @shipping_address.address_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @shipping_address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @shipping_address.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @shipping_address.country %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @shipping_address.zip %>
</p>

<p>
  <strong>Email:</strong>
  <%= @shipping_address.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @shipping_address.phone %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @shipping_address.customer %>
</p>

<p>
  <strong>Order:</strong>
  <%= @shipping_address.order %>
</p>

<%= link_to 'Edit', edit_shipping_address_path(@shipping_address) %> |
<%= link_to 'Back', shipping_addresses_path %>